q: [
  15.0, 15.0, 15.0,
  0.0, 0.0, 0.0,
  0.1, 0.1, 0.00,
  2.5e-1, 2.5e-1, 2.5e-1,
  0.01, 0.01, 0.01, 0.01,
]

r: [
  5.0e-1, 5.0e-1, 5.0e-1, 5.0e-1,
]

soft_penalty: 5.0e+3
horizon_sec: 0.7
ratio: 1
gate_prioritization: 4.0
max_iter: 2
wall_time_ratio: 0.8
wait_time_ratio: 220.2

constraints:
  min_thrust: 0.03
  max_thrust: 0.13
  max_thrust_change: 1.5
  gate_r: 0.15
  obstacle_r: 0.17
  min_z: 0.07
  max_tilt: 80 # degrees

planner:
  speed: 1.75
  gate_time_const: 0.1

drone_params:
  'quadrotor_mass': 0.03454
  'L': 0.046
  'g': 9.81
  'quadrotor_ixx_inertia': 1.4e-05
  'quadrotor_iyy_inertia': 1.4e-05
  'quadrotor_izz_inertia': 2.17e-05
  'quadrotor_kf': 3.16e-10
  'quadrotor_km': 7.94e-12

