q: [
  15.0, 15.0, 15.0,
  0.0, 0.0, 0.0,
  0.1, 0.1, 0.00,
  2.5e-1, 2.5e-1, 2.5e-1,
  0.01, 0.01, 0.01, 0.01,
]

r: [
  1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2,
]

soft_penalty: 5.0e+2
horizon_sec: 1.25
ratio: 8
gate_prioritization: 4.0
max_iter: 150
wall_time_ratio: 8000.8
wait_time_ratio: 2200.2

constraints:
  min_thrust: 0.03
  max_thrust: 0.12
  max_thrust_change: 1.0
  gate_r: 0.15
  obstacle_r: 0.18
  min_z: 0.07
  max_tilt: 80 # degrees

planner:
  speed: 1.0
  gate_time_const: 0.1

drone_params:
  'quadrotor_mass': 0.03454
  'L': 0.046
  'g': 9.81
  'quadrotor_ixx_inertia': 1.4e-05
  'quadrotor_iyy_inertia': 1.4e-05
  'quadrotor_izz_inertia': 2.17e-05
  'quadrotor_kf': 3.16e-10
  'quadrotor_km': 7.94e-12

