controller: diffusion

n_actions: 3
n_initial_actions: 16  # only used for buffered
offset: 1
wait_time_ratio: 0.2  # only used for async

diffusion:
  inference_steps: 5  # DDIM
  device: "cuda:0"

mpc:
  q: [
    15.0, 15.0, 15.0,
    0.0, 0.0, 0.0,
    0.1, 0.1, 1.0e-2,
    5.0e-1, 5.0e-1, 5.0e-1,
    0.01, 0.01, 0.01, 0.01,
  ]

  r: [
    1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2,  # 5.0e-1, 5.0e-1, 5.0e-1, 5.0e-1,  #
  ]

  # horizon_skip: 4  # deprecated because dangerous
  soft_penalty: 5.0e+2
  horizon_sec: 0.8
  gate_prioritization: 4.0
  max_iter: 5
  max_wall_time: 0.7

  constraints:
    min_thrust: 0.03  # N, single rotor
    max_thrust: 0.12  # N, single rotor
    max_thrust_change: 1.0  # max thrust/s, single rotor
    gate_r: 0.15  # m
    obstacle_r: 0.17  # m
    min_z: 0.07  # m
    max_tilt: 80  # deg

  planner:
    speed: 1.0  # m/s nominal
    gate_time_const: 0.1

  model:
    'quadrotor_mass': 0.03454
    'L': 0.046
    'g': 9.81
    'quadrotor_ixx_inertia': 1.4e-05
    'quadrotor_iyy_inertia': 1.4e-05
    'quadrotor_izz_inertia': 2.17e-05
    'quadrotor_kf': 3.16e-10
    'quadrotor_km': 7.94e-12



