planner:
  duration: 6.0  # [s]

estimator:
  estimate_state: False
  vicon_mask: [
    True,   # x
    False,  # x_dot
    True,   # y
    False,  # y_dot
    True,   # z
    False,  # z_dot
    True,   # phi
    True,   # theta
    True,   # psi
    False,  # p
    False,  # q
    False,  # r
  ]

mpc:
  q: [
    5.0, 5.0, 25.0,
    0.00, 0.00, 0.00,
    0.00, 0.00, 0.00,
    1.0e-2, 1.0e-2, 1.0e-2,
  ]

  r: [
    0.0, 0.0, 0.0, 0.0
  ]

  horizon_sec: 1.0

