name: drone_lowdim

obs_dim: 31 # 12 state + 1 next_gate + 6 * gates + 3 * obstacles
action_dim: 13
keypoint_dim: inf

dataset:
  _target_: diffusion_policy.dataset.drone_lowdim_dataset.DroneLowdimDataset
  zarr_path: output/race_data.npz
  horizon: ${horizon}
