name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs:
  online-competition:

    runs-on: ubuntu-latest
    env: # Or as an environment variable
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yaml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Install cffirmware
        run: |
          git clone -b drone_racing https://github.com/utiasDSL/pycffirmware.git
          cd pycffirmware
          git submodule update --init --recursive
          ./wrapper/build_linux.sh
      - run: pip install .[rl, test]
        shell: bash -el {0}
      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: bash -el {0}
      - name: Export with kaggle
        run: kaggle competitions submit lsy-drone-racing-ss24 -f submission.csv -m "Automated submission"
        shell: bash -el {0}

      